server {
    listen 80;
    server_name ec2.mdfahim.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ec2.mdfahim.dev;
    ssl_certificate /etc/letsencrypt/live/ec2.mdfahim.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ec2.mdfahim.dev/privkey.pem;

    add_header X-Frame-Options "DENY";
    add_header X-Content-Type-Options "nosniff";
    add_header Referrer-Policy "strict-origin-when-cross-origin";
    add_header Strict-Transport-Security "max-age=31536000; includeSubDomains";

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}