server {
    listen 80;
    server_name ec2.mdfahim.dev;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ec2.mdfahim.dev;

    ssl_certificate /etc/letsencrypt/live/ec2.mdfahim.dev/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/ec2.mdfahim.dev/privkey.pem;

    location / {
        root /usr/share/nginx/html;
        index index.html;
    }
}