name: Dependency Scan
on:
  push:
    branches: [main, staging]
jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: fahim017803/mdfahim.dev:latest
          format: json
          output: trivy-report.json
          exit-code: 0
      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-report-${{ github.run_number }}
          path: trivy-report.json
          retention-days: 90