name: Deploy Staging
on:
  push:
    branches: [staging]
jobs:
  deploy:
    runs-on: [self-hosted, Linux, X64, My-porfolio-staging]
    environment: staging
    steps:
      - uses: actions/checkout@v4
      - name: login to docker
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: deploy with docker compose
        run: |
          docker compose down
          docker compose pull
          docker compose up -d