name: Docker Lint
on:
  push:
    branches: [main, staging]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Lint Dockerfile
        uses: hadolint/hadolint-action@v3.1.0
        with:
          dockerfile: dockerfile
          format: json
          output-file: hadolint-report.json
          no-fail: true
      - name: Upload Hadolint Report
        uses: actions/upload-artifact@v4
        with:
          name: hadolint-report-${{ github.run_number }}
          path: hadolint-report.json
          retention-days: 90