name: Lighthouse CI
on:
  workflow_run:
    workflows: ["Deploy Portfolio"]
    types:
      - completed
jobs:
  lighthouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: |
            https://ec2.mdfahim.dev
          uploadArtifacts: true