name: OWASP ZAP Scan
on:
  workflow_run:
    workflows: ["Deploy Production"]
    types:
      - completed
jobs:
  zap-scan:
    runs-on: ubuntu-latest
    steps:
      - name: ZAP Scan
        uses: zaproxy/action-baseline@v0.12.0
        with:
          target: 'https://ec2.mdfahim.dev'
          fail_action: false