name: SSL Check
on:
  schedule:
    - cron: '0 9 * * 1'
  workflow_dispatch:
jobs:
  ssl:
    runs-on: ubuntu-latest
    steps:
      - name: Check SSL certificate
        run: |
          curl -vI https://ec2.mdfahim.dev 2>&1 | grep -E "expire|issuer|subject"